INSERT INTO first_names (name, is_male_name, is_female_name) VALUES
 ('Aldric', true, false),
 ('Aldwin', true, false),
 ('Alaric', true, false),
 ('Alastair', true, false),
 ('Alberic', true, false),
 ('Alden', true, false),
 ('Alfred', true, false),
 ('Alric', true, false),
 ('Ambrose', true, false),
 ('Ansel', true, false),
 ('Arden', true, true),
 ('Armand', true, false),
 ('Arthur', true, false),
 ('Asher', true, false),
 ('August', true, false),
 ('Baldwin', true, false),
 ('Bartholomew', true, false),
 ('Basil', true, false),
 ('Bastian', true, false),
 ('Beaumont', true, false),
 ('Benedict', true, false),
 ('Bertram', true, false),
 ('Blaise', true, false),
 ('Bram', true, false),
 ('Brandon', true, false),
 ('Cedric', true, false),
 ('Caldwell', true, false),
 ('Callum', true, false),
 ('Casper', true, false),
 ('Cecil', true, false),
 ('Cedran', true, false),
 ('Charles', true, false),
 ('Crispin', true, false),
 ('Cuthbert', true, false),
 ('Cyprian', true, false),
 ('Darian', true, true),
 ('Darius', true, false),
 ('David', true, false),
 ('Edgar', true, false),
 ('Edmund', true, false),
 ('Edric', true, false),
 ('Edward', true, false),
 ('Edwin', true, false),
 ('Elias', true, false),
 ('Elric', true, false),
 ('Emeric', true, false),
 ('Emrys', true, false),
 ('Ernest', true, false),
 ('Everard', true, false),
 ('Everett', true, false),
 ('Ezekiel', true, false),
 ('Fabian', true, false),
 ('Felix', true, false),
 ('Ferdinand', true, false),
 ('Finn', true, false),
 ('Florian', true, false),
 ('Francis', true, false),
 ('Frederic', true, false),
 ('Frederick', true, false),
 ('Gareth', true, false),
 ('Garrick', true, false),
 ('Geoffrey', true, false),
 ('Gerald', true, false),
 ('Gerard', true, false),
 ('Gilbert', true, false),
 ('Godfrey', true, false),
 ('Graham', true, false),
 ('Gregory', true, false),
 ('Griffin', true, false),
 ('Hadrian', true, false),
 ('Haldor', true, false),
 ('Harold', true, false),
 ('Harwin', true, false),
 ('Hector', true, false),
 ('Henry', true, false),
 ('Herbert', true, false),
 ('Hugh', true, false),
 ('Humphrey', true, false),
 ('Ian', true, false),
 ('Isaac', true, false),
 ('Isidore', true, false),
 ('Ivan', true, false),
 ('Jasper', true, false),
 ('Jerome', true, false),
 ('Joachim', true, false),
 ('John', true, false),
 ('Jonas', true, false),
 ('Jonathan', true, false),
 ('Joseph', true, false),
 ('Julian', true, false),
 ('Julius', true, false),
 ('Justus', true, false),
 ('Kendrick', true, false),
 ('Kenneth', true, false),
 ('Lambert', true, false),
 ('Lancelot', true, false),
 ('Laurence', true, false),
 ('Leander', true, false),
 ('Leofric', true, false),
 ('Leonard', true, false),
 ('Leonard', true, false),
 ('Leopold', true, false),
 ('Lothar', true, false),
 ('Lucian', true, false),
 ('Magnus', true, false),
 ('Malcolm', true, false),
 ('Marcus', true, false),
 ('Martin', true, false),
 ('Matthias', true, false),
 ('Matthew', true, false),
 ('Maurice', true, false),
 ('Maximilian', true, false),
 ('Miles', true, false),
 ('Montague', true, false),
 ('Nathaniel', true, false),
 ('Nicholas', true, false),
 ('Nigel', true, false),
 ('Oliver', true, false),
 ('Osric', true, false),
 ('Oswald', true, false),
 ('Oswin', true, false),
 ('Otto', true, false),
 ('Percival', true, false),
 ('Peter', true, false),
 ('Philip', true, false),
 ('Quentin', true, false),
 ('Ralph', true, false),
 ('Randall', true, false),
 ('Reginald', true, false),
 ('Reinhold', true, false),
 ('Richard', true, false),
 ('Robert', true, false),
 ('Robin', true, true),
 ('Roderick', true, false),
 ('Roland', true, false),
 ('Rowan', true, true),
 ('Rupert', true, false),
 ('Sebastian', true, false),
 ('Silas', true, false),
 ('Simon', true, false),
 ('Stephen', true, false),
 ('Sylvester', true, false),
 ('Theobald', true, false),
 ('Theodore', true, false),
 ('Thomas', true, false),
 ('Tobias', true, false),
 ('Tristan', true, false),
 ('Ulric', true, false),
 ('Valerian', true, false),
 ('Victor', true, false),
 ('Vincent', true, false),
 ('Walter', true, false),
 ('Warren', true, false),
 ('Wesley', true, false),
 ('Wilbur', true, false),
 ('William', true, false),
 ('Wulfric', true, false),
 ('Zachariah', true, false),
 ('Abigail', false, true),
 ('Adelaide', false, true),
 ('Adela', false, true),
 ('Adeline', false, true),
 ('Agatha', false, true),
 ('Agnes', false, true),
 ('Aileen', false, true),
 ('Alice', false, true),
 ('Alina', false, true),
 ('Amelia', false, true),
 ('Amelie', false, true),
 ('Anastasia', false, true),
 ('Anabel', false, true),
 ('Annabel', false, true),
 ('Angelica', false, true),
 ('Anna', false, true),
 ('Anne', false, true),
 ('Arabella', false, true),
 ('Arabelle', false, true),
 ('Ariella', false, true),
 ('Astrid', false, true),
 ('Audrey', false, true),
 ('Beatrice', false, true),
 ('Beatrix', false, true),
 ('Berenice', false, true),
 ('Bertha', false, true),
 ('Bethany', false, true),
 ('Bridget', false, true),
 ('Bronwen', false, true),
 ('Cassandra', false, true),
 ('Cecily', false, true),
 ('Celeste', false, true),
 ('Celia', false, true),
 ('Celine', false, true),
 ('Charity', false, true),
 ('Charlotte', false, true),
 ('Christina', false, true),
 ('Cicely', false, true),
 ('Clara', false, true),
 ('Clarissa', false, true),
 ('Claudia', false, true),
 ('Constance', false, true),
 ('Cordelia', false, true),
 ('Cressida', false, true),
 ('Daphne', false, true),
 ('Delia', false, true),
 ('Diana', false, true),
 ('Dorothea', false, true),
 ('Edith', false, true),
 ('Eleanor', false, true),
 ('Elena', false, true),
 ('Elinor', false, true),
 ('Elizabeth', false, true),
 ('Ella', false, true),
 ('Eloise', false, true),
 ('Elsie', false, true),
 ('Elspeth', false, true),
 ('Emilia', false, true),
 ('Emmeline', false, true),
 ('Emma', false, true),
 ('Esther', false, true),
 ('Evelyn', false, true),
 ('Felicity', false, true),
 ('Flora', false, true),
 ('Florence', false, true),
 ('Frances', false, true),
 ('Freya', false, true),
 ('Genevieve', false, true),
 ('Georgina', false, true),
 ('Gertrude', false, true),
 ('Giselle', false, true),
 ('Grace', false, true),
 ('Guinevere', false, true),
 ('Gwendolyn', false, true),
 ('Hannah', false, true),
 ('Harriet', false, true),
 ('Hawise', false, true),
 ('Helena', false, true),
 ('Henrietta', false, true),
 ('Honora', false, true),
 ('Ida', false, true),
 ('Imogen', false, true),
 ('Ingrid', false, true),
 ('Irene', false, true),
 ('Isabel', false, true),
 ('Isabella', false, true),
 ('Isolde', false, true),
 ('Jacqueline', false, true),
 ('Jane', false, true),
 ('Joan', false, true),
 ('Josephine', false, true),
 ('Judith', false, true),
 ('Juliana', false, true),
 ('Juliette', false, true),
 ('Katherine', false, true),
 ('Katrina', false, true),
 ('Lavinia', false, true),
 ('Leonora', false, true),
 ('Lillian', false, true),
 ('Lily', false, true),
 ('Lorelei', false, true),
 ('Louisa', false, true),
 ('Lucia', false, true),
 ('Lucille', false, true),
 ('Madeleine', false, true),
 ('Margaret', false, true),
 ('Marguerite', false, true),
 ('Marian', false, true),
 ('Marianne', false, true),
 ('Matilda', false, true),
 ('Maud', false, true),
 ('Melisande', false, true),
 ('Mirabel', false, true),
 ('Miranda', false, true),
 ('Miriam', false, true),
 ('Morgana', false, true),
 ('Nadia', false, true),
 ('Natalia', false, true),
 ('Nicola', false, true),
 ('Odette', false, true),
 ('Olivia', false, true),
 ('Ophelia', false, true),
 ('Ottilie', false, true),
 ('Penelope', false, true),
 ('Philippa', false, true),
 ('Priscilla', false, true),
 ('Rosalind', false, true),
 ('Rosamund', false, true),
 ('Rose', false, true),
 ('Rowena', false, true),
 ('Sabina', false, true),
 ('Sabrina', false, true),
 ('Seraphina', false, true),
 ('Sibyl', false, true),
 ('Sophia', false, true),
 ('Susanna', false, true),
 ('Sylvia', false, true),
 ('Tabitha', false, true),
 ('Theodora', false, true),
 ('Ursula', false, true),
 ('Valentina', false, true),
 ('Veronica', false, true),
 ('Victoria', false, true),
 ('Vivian', false, true),
 ('Winifred', false, true),
 ('Yolanda', false, true),
 ('Ysabel', false, true),
 ('Avery', true, true),
 ('Bailey', true, true),
 ('Blair', true, true),
 ('Briar', true, true),
 ('Brook', true, true),
 ('Cameron', true, true),
 ('Casey', true, true),
 ('Cassidy', true, true),
 ('Dale', true, true),
 ('Darian', true, true),
 ('Devon', true, true),
 ('Ellis', true, true),
 ('Emery', true, true),
 ('Evan', true, true),
 ('Finley', true, true),
 ('Harley', true, true),
 ('Hayden', true, true),
 ('Jamie', true, true),
 ('Jesse', true, true),
 ('Jordan', true, true),
 ('Kelsey', true, true),
 ('Kendall', true, true),
 ('Lane', true, true),
 ('Lesley', true, true),
 ('Linden', true, true),
 ('Loren', true, true),
 ('Morgan', true, true),
 ('Parker', true, true),
 ('Payton', true, true),
 ('Quinn', true, true),
 ('Reese', true, true),
 ('Riley', true, true),
 ('River', true, true),
 ('Rory', true, true),
 ('Sage', true, true),
 ('Shannon', true, true),
 ('Shay', true, true),
 ('Shelby', true, true),
 ('Skyler', true, true),
 ('Spencer', true, true),
 ('Taylor', true, true),
 ('Teagan', true, true),
 ('Terry', true, true),
 ('Tristan', true, true),
 ('Val', true, true),
 ('Winter', true, true),
 ('Wren', true, true);

INSERT INTO last_names (name, surname_type) VALUES
-- COMMON
('Alden', 'COMMON'),
('Archer', 'COMMON'),
('Ashby', 'COMMON'),
('Barton', 'COMMON'),
('Bell', 'COMMON'),
('Bennett', 'COMMON'),
('Brooks', 'COMMON'),
('Burton', 'COMMON'),
('Carter', 'COMMON'),
('Clark', 'COMMON'),
('Cole', 'COMMON'),
('Collins', 'COMMON'),
('Cooper', 'COMMON'),
('Dale', 'COMMON'),
('Dawson', 'COMMON'),
('Ellis', 'COMMON'),
('Everett', 'COMMON'),
('Foster', 'COMMON'),
('Gibson', 'COMMON'),
('Grant', 'COMMON'),
('Hale', 'COMMON'),
('Harris', 'COMMON'),
('Hayes', 'COMMON'),
('Henderson', 'COMMON'),
('Holland', 'COMMON'),
('Hudson', 'COMMON'),
('Jackson', 'COMMON'),
('Jordan', 'COMMON'),
('Lawson', 'COMMON'),
('Marshall', 'COMMON'),
('Mason', 'COMMON'),
('Morgan', 'COMMON'),
('Nash', 'COMMON'),
('Parker', 'COMMON'),
('Reed', 'COMMON'),
('Reeve', 'COMMON'),
('Rowe', 'COMMON'),
('Russell', 'COMMON'),
('Turner', 'COMMON'),
('Walker', 'COMMON'),

-- OCCUPATIONAL
('Baker', 'OCCUPATIONAL'),
('Brewer', 'OCCUPATIONAL'),
('Butcher', 'OCCUPATIONAL'),
('Carpenter', 'OCCUPATIONAL'),
('Chandler', 'OCCUPATIONAL'),
('Cook', 'OCCUPATIONAL'),
('Cooper', 'OCCUPATIONAL'),
('Fletcher', 'OCCUPATIONAL'),
('Fowler', 'OCCUPATIONAL'),
('Fisher', 'OCCUPATIONAL'),
('Gardener', 'OCCUPATIONAL'),
('Glover', 'OCCUPATIONAL'),
('Hunter', 'OCCUPATIONAL'),
('Miller', 'OCCUPATIONAL'),
('Potter', 'OCCUPATIONAL'),
('Shepherd', 'OCCUPATIONAL'),
('Smith', 'OCCUPATIONAL'),
('Squire', 'OCCUPATIONAL'),
('Thatcher', 'OCCUPATIONAL'),
('Weaver', 'OCCUPATIONAL'),
('Wheeler', 'OCCUPATIONAL'),
('Wright', 'OCCUPATIONAL'),
('Tanner', 'OCCUPATIONAL'),
('Tailor', 'OCCUPATIONAL'),
('Cobbler', 'OCCUPATIONAL'),
('Dyer', 'OCCUPATIONAL'),
('Miner', 'OCCUPATIONAL'),
('Sailor', 'OCCUPATIONAL'),
('Slater', 'OCCUPATIONAL'),
('Woodman', 'OCCUPATIONAL'),
('Armstrong', 'OCCUPATIONAL'),
('Bowman', 'OCCUPATIONAL'),
('Fowler', 'OCCUPATIONAL'),
('Page', 'OCCUPATIONAL'),
('Porter', 'OCCUPATIONAL'),
('Sexton', 'OCCUPATIONAL'),
('Steward', 'OCCUPATIONAL'),
('Chamberlain', 'OCCUPATIONAL'),
('Herald', 'OCCUPATIONAL'),
('Messenger', 'OCCUPATIONAL'),

-- LOCATIONAL
('Ashford', 'LOCATIONAL'),
('Ashworth', 'LOCATIONAL'),
('Blackburn', 'LOCATIONAL'),
('Blackwell', 'LOCATIONAL'),
('Bridgewater', 'LOCATIONAL'),
('Brookfield', 'LOCATIONAL'),
('Brookshire', 'LOCATIONAL'),
('Castleford', 'LOCATIONAL'),
('Claybourne', 'LOCATIONAL'),
('Coldwater', 'LOCATIONAL'),
('Cranford', 'LOCATIONAL'),
('Eastwood', 'LOCATIONAL'),
('Fairfield', 'LOCATIONAL'),
('Foxford', 'LOCATIONAL'),
('Greenfield', 'LOCATIONAL'),
('Greenwood', 'LOCATIONAL'),
('Hartford', 'LOCATIONAL'),
('Highfield', 'LOCATIONAL'),
('Hillcrest', 'LOCATIONAL'),
('Kingsley', 'LOCATIONAL'),
('Lakewood', 'LOCATIONAL'),
('Longford', 'LOCATIONAL'),
('Meadowcroft', 'LOCATIONAL'),
('Millbrook', 'LOCATIONAL'),
('Oakford', 'LOCATIONAL'),
('Oakley', 'LOCATIONAL'),
('Ravenwood', 'LOCATIONAL'),
('Redford', 'LOCATIONAL'),
('Ridgeway', 'LOCATIONAL'),
('Riverdale', 'LOCATIONAL'),
('Rosewood', 'LOCATIONAL'),
('Stonebridge', 'LOCATIONAL'),
('Stonefield', 'LOCATIONAL'),
('Stoneford', 'LOCATIONAL'),
('Thornfield', 'LOCATIONAL'),
('Underhill', 'LOCATIONAL'),
('Westbrook', 'LOCATIONAL'),
('Westfield', 'LOCATIONAL'),
('Whitfield', 'LOCATIONAL'),
('Woodbridge', 'LOCATIONAL'),

-- DESCRIPTIVE
('Black', 'DESCRIPTIVE'),
('Blackwood', 'DESCRIPTIVE'),
('Bright', 'DESCRIPTIVE'),
('Brown', 'DESCRIPTIVE'),
('Cold', 'DESCRIPTIVE'),
('Fair', 'DESCRIPTIVE'),
('Grey', 'DESCRIPTIVE'),
('Green', 'DESCRIPTIVE'),
('Hardy', 'DESCRIPTIVE'),
('Keen', 'DESCRIPTIVE'),
('Long', 'DESCRIPTIVE'),
('Little', 'DESCRIPTIVE'),
('Quick', 'DESCRIPTIVE'),
('Red', 'DESCRIPTIVE'),
('Sharp', 'DESCRIPTIVE'),
('Short', 'DESCRIPTIVE'),
('Silver', 'DESCRIPTIVE'),
('Small', 'DESCRIPTIVE'),
('Strong', 'DESCRIPTIVE'),
('Swift', 'DESCRIPTIVE'),
('Tall', 'DESCRIPTIVE'),
('White', 'DESCRIPTIVE'),
('Wise', 'DESCRIPTIVE'),
('Young', 'DESCRIPTIVE'),
('Fox', 'DESCRIPTIVE'),
('Hawk', 'DESCRIPTIVE'),
('Wolf', 'DESCRIPTIVE'),
('Bear', 'DESCRIPTIVE'),
('Raven', 'DESCRIPTIVE'),
('Crow', 'DESCRIPTIVE'),

-- NOBLE
('Ashbourne', 'NOBLE'),
('Ashcombe', 'NOBLE'),
('Ashdown', 'NOBLE'),
('Blackmere', 'NOBLE'),
('Blackthorn', 'NOBLE'),
('Bloodworth', 'NOBLE'),
('Caldwell', 'NOBLE'),
('Cavendish', 'NOBLE'),
('Cromwell', 'NOBLE'),
('Darkmoor', 'NOBLE'),
('Fairfax', 'NOBLE'),
('Fairmont', 'NOBLE'),
('Grantham', 'NOBLE'),
('Hawthorne', 'NOBLE'),
('Haverford', 'NOBLE'),
('Kingsbridge', 'NOBLE'),
('Lancaster', 'NOBLE'),
('Marlowe', 'NOBLE'),
('Montague', 'NOBLE'),
('Mortimer', 'NOBLE'),
('Northumberland', 'NOBLE'),
('Ravenscroft', 'NOBLE'),
('Redwyne', 'NOBLE'),
('Rosemont', 'NOBLE'),
('Rothwell', 'NOBLE'),
('Somerset', 'NOBLE'),
('Stirling', 'NOBLE'),
('Templeton', 'NOBLE'),
('Valemont', 'NOBLE'),
('Westmore', 'NOBLE'),
('Whitmore', 'NOBLE'),
('Wyndham', 'NOBLE'),
('Wynchester', 'NOBLE'),
('Winterbourne', 'NOBLE'),
('Wintermere', 'NOBLE'),
('Wolfe', 'NOBLE'),
('Yorke', 'NOBLE'),
('Aldermere', 'NOBLE'),
('Briarwood', 'NOBLE'),
('Stormvale', 'NOBLE');


INSERT INTO occupations
(job_title, monthly_wage, is_legal, prestige, danger, minimum_age_in_months, minimum_social_class, required_education)
VALUES

-- ============================================================
-- FARMING & AGRICULTURE
-- ============================================================

('Farm Labourer', 18.0, true, 10, 20, 144, 'PEASANT', 'NONE'),
('Field Worker', 15.0, true, 8, 15, 120, 'PEASANT', 'NONE'),
('Shepherd', 20.0, true, 12, 25, 144, 'PEASANT', 'NONE'),
('Goatherd', 18.0, true, 10, 20, 120, 'PEASANT', 'NONE'),
('Cattle Herder', 22.0, true, 15, 30, 144, 'PEASANT', 'NONE'),
('Pig Keeper', 17.0, true, 8, 15, 120, 'PEASANT', 'NONE'),
('Stable Hand', 20.0, true, 15, 25, 144, 'PEASANT', 'NONE'),
('Farm Steward', 35.0, true, 30, 20, 180, 'COMMONER', 'BASIC'),
('Orchard Keeper', 24.0, true, 15, 20, 144, 'PEASANT', 'NONE'),
('Vineyard Worker', 24.0, true, 18, 20, 144, 'PEASANT', 'NONE'),

-- ============================================================
-- FOOD & HOSPITALITY
-- ============================================================

('Baker', 32.0, true, 25, 15, 168, 'COMMONER', 'APPRENTICESHIP'),
('Butcher', 38.0, true, 30, 25, 168, 'COMMONER', 'APPRENTICESHIP'),
('Brewer', 35.0, true, 25, 15, 168, 'COMMONER', 'APPRENTICESHIP'),
('Cook', 30.0, true, 25, 15, 168, 'COMMONER', 'APPRENTICESHIP'),
('Tavern Keeper', 55.0, true, 40, 25, 216, 'COMMONER', 'BASIC'),
('Innkeeper', 60.0, true, 45, 25, 216, 'COMMONER', 'BASIC'),
('Kitchen Servant', 16.0, true, 8, 10, 120, 'PEASANT', 'NONE'),
('Tavern Servant', 18.0, true, 10, 20, 120, 'PEASANT', 'NONE'),
('Food Seller', 25.0, true, 20, 15, 144, 'COMMONER', 'NONE'),

-- ============================================================
-- CRAFTS & TRADES
-- ============================================================

('Blacksmith', 65.0, true, 45, 40, 180, 'COMMONER', 'APPRENTICESHIP'),
('Armourer', 75.0, true, 55, 45, 216, 'COMMONER', 'APPRENTICESHIP'),
('Weaponsmith', 80.0, true, 60, 45, 216, 'COMMONER', 'APPRENTICESHIP'),
('Carpenter', 48.0, true, 35, 30, 168, 'COMMONER', 'APPRENTICESHIP'),
('Mason', 55.0, true, 40, 45, 180, 'COMMONER', 'APPRENTICESHIP'),
('Stonecutter', 52.0, true, 35, 55, 180, 'COMMONER', 'APPRENTICESHIP'),
('Potter', 35.0, true, 25, 25, 168, 'COMMONER', 'APPRENTICESHIP'),
('Weaver', 38.0, true, 30, 15, 168, 'COMMONER', 'APPRENTICESHIP'),
('Tailor', 45.0, true, 40, 10, 180, 'COMMONER', 'APPRENTICESHIP'),
('Shoemaker', 40.0, true, 30, 15, 168, 'COMMONER', 'APPRENTICESHIP'),
('Tanner', 42.0, true, 25, 25, 168, 'COMMONER', 'APPRENTICESHIP'),
('Dyer', 40.0, true, 25, 20, 168, 'COMMONER', 'APPRENTICESHIP'),
('Cooper', 42.0, true, 30, 25, 168, 'COMMONER', 'APPRENTICESHIP'),
('Rope Maker', 30.0, true, 20, 15, 156, 'COMMONER', 'APPRENTICESHIP'),
('Glassmaker', 60.0, true, 45, 50, 192, 'COMMONER', 'APPRENTICESHIP'),
('Jeweller', 90.0, true, 65, 15, 216, 'MERCHANT', 'APPRENTICESHIP'),

-- ============================================================
-- MINING & DANGEROUS LABOUR
-- ============================================================

('Miner', 45.0, true, 25, 80, 168, 'PEASANT', 'NONE'),
('Coal Miner', 48.0, true, 25, 85, 168, 'PEASANT', 'NONE'),
('Quarry Worker', 42.0, true, 20, 65, 156, 'PEASANT', 'NONE'),
('Salt Miner', 50.0, true, 30, 60, 168, 'PEASANT', 'NONE'),
('Prospector', 55.0, true, 40, 70, 216, 'COMMONER', 'BASIC'),
('Tunnel Worker', 38.0, true, 15, 75, 156, 'PEASANT', 'NONE'),

-- ============================================================
-- FORESTRY & HUNTING
-- ============================================================

('Woodcutter', 28.0, true, 15, 55, 144, 'PEASANT', 'NONE'),
('Lumberjack', 32.0, true, 20, 65, 168, 'PEASANT', 'NONE'),
('Hunter', 45.0, true, 35, 65, 168, 'PEASANT', 'BASIC'),
('Trapper', 38.0, true, 25, 55, 156, 'PEASANT', 'NONE'),
('Forester', 50.0, true, 40, 45, 192, 'COMMONER', 'BASIC'),
('Royal Huntsman', 110.0, true, 75, 60, 216, 'NOBLE', 'BASIC'),

-- ============================================================
-- MERCHANTS & COMMERCE
-- ============================================================

('Street Vendor', 28.0, true, 18, 25, 144, 'COMMONER', 'NONE'),
('Market Seller', 35.0, true, 25, 25, 168, 'COMMONER', 'BASIC'),
('Shopkeeper', 65.0, true, 45, 20, 216, 'MERCHANT', 'BASIC'),
('Merchant', 90.0, true, 60, 35, 240, 'MERCHANT', 'BASIC'),
('Trader', 85.0, true, 55, 40, 216, 'MERCHANT', 'BASIC'),
('Spice Merchant', 120.0, true, 70, 40, 240, 'MERCHANT', 'LITERATE'),
('Cloth Merchant', 110.0, true, 65, 25, 240, 'MERCHANT', 'LITERATE'),
('Wine Merchant', 100.0, true, 60, 30, 240, 'MERCHANT', 'BASIC'),
('Master Merchant', 160.0, true, 75, 30, 300, 'MERCHANT', 'LITERATE'),
('Moneylender', 140.0, true, 55, 20, 300, 'MERCHANT', 'LITERATE'),

-- ============================================================
-- TRANSPORT & TRAVEL
-- ============================================================

('Cart Driver', 30.0, true, 15, 35, 156, 'PEASANT', 'NONE'),
('Caravan Guard', 55.0, true, 35, 70, 180, 'COMMONER', 'BASIC'),
('Caravan Master', 95.0, true, 55, 55, 240, 'MERCHANT', 'BASIC'),
('Ferryman', 35.0, true, 20, 40, 168, 'PEASANT', 'NONE'),
('Boatman', 38.0, true, 25, 45, 168, 'PEASANT', 'NONE'),
('Sailor', 42.0, true, 30, 60, 168, 'COMMONER', 'NONE'),
('Shipwright', 70.0, true, 50, 45, 216, 'COMMONER', 'APPRENTICESHIP'),
('Navigator', 100.0, true, 65, 55, 240, 'COMMONER', 'LITERATE'),

-- ============================================================
-- DOMESTIC SERVICE
-- ============================================================

('Servant', 15.0, true, 5, 10, 120, 'PEASANT', 'NONE'),
('Housemaid', 16.0, true, 8, 10, 120, 'PEASANT', 'NONE'),
('Footman', 22.0, true, 15, 15, 168, 'COMMONER', 'NONE'),
('Butler', 65.0, true, 50, 10, 240, 'COMMONER', 'BASIC'),
('Housekeeper', 45.0, true, 35, 10, 216, 'COMMONER', 'BASIC'),
('Chambermaid', 18.0, true, 8, 10, 120, 'PEASANT', 'NONE'),
('Governess', 75.0, true, 60, 10, 240, 'COMMONER', 'LITERATE'),
('Valet', 50.0, true, 40, 10, 216, 'COMMONER', 'BASIC'),
('Stablemaster', 55.0, true, 35, 30, 216, 'COMMONER', 'BASIC'),

-- ============================================================
-- EDUCATION & WRITING
-- ============================================================

('Scribe', 65.0, true, 55, 10, 180, 'COMMONER', 'LITERATE'),
('Copyist', 55.0, true, 45, 10, 180, 'COMMONER', 'LITERATE'),
('Tutor', 80.0, true, 65, 10, 216, 'COMMONER', 'SCHOLARLY'),
('Schoolteacher', 70.0, true, 55, 10, 216, 'COMMONER', 'LITERATE'),
('Scholar', 90.0, true, 75, 10, 240, 'COMMONER', 'SCHOLARLY'),
('Historian', 100.0, true, 80, 5, 300, 'NOBLE', 'SCHOLARLY'),
('Librarian', 75.0, true, 65, 5, 240, 'COMMONER', 'SCHOLARLY'),
('Cartographer', 110.0, true, 75, 20, 240, 'MERCHANT', 'SCHOLARLY'),

-- ============================================================
-- RELIGIOUS
-- ============================================================

('Temple Servant', 20.0, true, 20, 10, 144, 'PEASANT', 'BASIC'),
('Acolyte', 25.0, true, 30, 10, 144, 'COMMONER', 'BASIC'),
('Priest', 70.0, true, 70, 10, 216, 'COMMONER', 'LITERATE'),
('Senior Priest', 110.0, true, 80, 10, 300, 'COMMONER', 'SCHOLARLY'),
('Monk', 35.0, true, 45, 10, 216, 'COMMONER', 'LITERATE'),
('Nun', 35.0, true, 45, 10, 216, 'COMMONER', 'LITERATE'),
('Abbot', 120.0, true, 85, 10, 360, 'NOBLE', 'SCHOLARLY'),
('Abbess', 120.0, true, 85, 10, 360, 'NOBLE', 'SCHOLARLY'),
('Religious Scholar', 95.0, true, 80, 10, 264, 'COMMONER', 'SCHOLARLY'),

-- ============================================================
-- MEDICINE
-- ============================================================

('Herbalist', 45.0, true, 40, 15, 192, 'COMMONER', 'APPRENTICESHIP'),
('Healer', 70.0, true, 60, 20, 216, 'COMMONER', 'LITERATE'),
('Physician', 130.0, true, 85, 15, 300, 'MERCHANT', 'SCHOLARLY'),
('Surgeon', 120.0, true, 75, 50, 300, 'MERCHANT', 'SCHOLARLY'),
('Midwife', 55.0, true, 50, 35, 216, 'COMMONER', 'APPRENTICESHIP'),
('Apothecary', 85.0, true, 65, 20, 240, 'MERCHANT', 'LITERATE'),

-- ============================================================
-- MILITARY
-- ============================================================

('Camp Follower', 20.0, true, 10, 55, 144, 'PEASANT', 'NONE'),
('Foot Soldier', 45.0, true, 30, 75, 180, 'COMMONER', 'NONE'),
('Archer', 50.0, true, 35, 70, 180, 'COMMONER', 'BASIC'),
('Crossbowman', 55.0, true, 40, 70, 180, 'COMMONER', 'BASIC'),
('Spearman', 48.0, true, 30, 75, 180, 'COMMONER', 'NONE'),
('Cavalryman', 75.0, true, 55, 75, 216, 'COMMONER', 'BASIC'),
('Sergeant', 80.0, true, 55, 70, 240, 'COMMONER', 'BASIC'),
('Captain', 130.0, true, 70, 70, 300, 'NOBLE', 'LITERATE'),
('Commander', 180.0, true, 80, 65, 360, 'NOBLE', 'LITERATE'),
('Knight', 150.0, true, 85, 80, 216, 'NOBLE', 'APPRENTICESHIP'),
('Knight Commander', 220.0, true, 90, 80, 360, 'NOBLE', 'LITERATE'),
('Royal Guard', 180.0, true, 90, 85, 240, 'NOBLE', 'BASIC'),
('Royal Guard Captain', 250.0, true, 95, 80, 360, 'NOBLE', 'LITERATE'),

-- ============================================================
-- LAW & JUSTICE
-- ============================================================

('Watchman', 35.0, true, 30, 55, 180, 'COMMONER', 'NONE'),
('Town Guard', 45.0, true, 35, 60, 180, 'COMMONER', 'BASIC'),
('Constable', 70.0, true, 55, 55, 240, 'COMMONER', 'LITERATE'),
('Sheriff', 120.0, true, 75, 50, 300, 'NOBLE', 'LITERATE'),
('Judge', 160.0, true, 90, 20, 360, 'NOBLE', 'SCHOLARLY'),
('Magistrate', 140.0, true, 85, 25, 300, 'NOBLE', 'SCHOLARLY'),
('Bailiff', 75.0, true, 50, 30, 240, 'COMMONER', 'LITERATE'),
('Jailer', 55.0, true, 30, 50, 216, 'COMMONER', 'BASIC'),
('Executioner', 70.0, true, 35, 70, 216, 'COMMONER', 'NONE'),

-- ============================================================
-- CRIME
-- ============================================================

('Thief', 35.0, false, 5, 65, 144, 'PEASANT', 'NONE'),
('Pickpocket', 30.0, false, 5, 55, 120, 'PEASANT', 'NONE'),
('Burglar', 60.0, false, 10, 70, 168, 'PEASANT', 'NONE'),
('Smuggler', 90.0, false, 15, 75, 216, 'COMMONER', 'BASIC'),
('Poacher', 40.0, false, 10, 55, 144, 'PEASANT', 'NONE'),
('Bandit', 75.0, false, 5, 90, 168, 'PEASANT', 'NONE'),
('Highway Robber', 85.0, false, 5, 90, 180, 'COMMONER', 'NONE'),
('Fence', 100.0, false, 20, 55, 240, 'MERCHANT', 'BASIC'),
('Blackmailer', 110.0, false, 15, 45, 240, 'COMMONER', 'LITERATE'),
('Assassin', 200.0, false, 10, 100, 216, 'COMMONER', 'APPRENTICESHIP'),

-- ============================================================
-- ENTERTAINMENT
-- ============================================================

('Minstrel', 45.0, true, 45, 25, 156, 'COMMONER', 'BASIC'),
('Musician', 50.0, true, 40, 20, 156, 'COMMONER', 'APPRENTICESHIP'),
('Bard', 80.0, true, 65, 30, 180, 'COMMONER', 'LITERATE'),
('Jester', 55.0, true, 45, 20, 168, 'COMMONER', 'BASIC'),
('Actor', 45.0, true, 35, 20, 156, 'COMMONER', 'BASIC'),
('Storyteller', 40.0, true, 35, 15, 168, 'COMMONER', 'BASIC'),
('Dancer', 35.0, true, 30, 20, 144, 'COMMONER', 'NONE'),

-- ============================================================
-- GUILDS & PROFESSIONS
-- ============================================================

('Guild Apprentice', 15.0, true, 15, 15, 144, 'COMMONER', 'NONE'),
('Guild Journeyman', 40.0, true, 30, 20, 192, 'COMMONER', 'APPRENTICESHIP'),
('Guild Master', 100.0, true, 65, 15, 300, 'MERCHANT', 'APPRENTICESHIP'),
('Master Craftsman', 110.0, true, 70, 20, 300, 'MERCHANT', 'APPRENTICESHIP'),
('Guild Treasurer', 130.0, true, 70, 15, 300, 'MERCHANT', 'LITERATE'),

-- ============================================================
-- NOBILITY
-- ============================================================

('Noble Steward', 150.0, true, 75, 20, 300, 'NOBLE', 'LITERATE'),
('Courtier', 180.0, true, 80, 15, 240, 'NOBLE', 'LITERATE'),
('Royal Courtier', 220.0, true, 90, 15, 300, 'NOBLE', 'SCHOLARLY'),
('Royal Treasurer', 300.0, true, 95, 15, 360, 'NOBLE', 'SCHOLARLY'),
('Royal Advisor', 350.0, true, 95, 10, 360, 'NOBLE', 'SCHOLARLY'),
('Diplomat', 250.0, true, 90, 25, 300, 'NOBLE', 'SCHOLARLY'),
('Ambassador', 300.0, true, 95, 35, 360, 'NOBLE', 'SCHOLARLY'),
('Lord', 400.0, true, 95, 20, 300, 'NOBLE', 'LITERATE'),
('Lady', 400.0, true, 95, 15, 300, 'NOBLE', 'LITERATE'),

-- ============================================================
-- ROYALTY
-- ============================================================

('Prince', 600.0, true, 100, 35, 216, 'ROYALTY', 'NONE'),
('Princess', 600.0, true, 100, 30, 216, 'ROYALTY', 'NONE'),
('Duke', 550.0, true, 100, 30, 300, 'NOBLE', 'LITERATE'),
('Duchess', 550.0, true, 100, 25, 300, 'NOBLE', 'LITERATE'),
('King', 1000.0, true, 100, 50, 360, 'ROYALTY', 'SCHOLARLY'),
('Queen', 1000.0, true, 100, 45, 360, 'ROYALTY', 'SCHOLARLY'),

-- ============================================================
-- SPECIAL / UNEMPLOYED
-- ============================================================

('Unemployed', 0.0, true, 0, 0, 0, 'PEASANT', 'NONE'),
('Beggar', 2.0, true, 0, 20, 144, 'PEASANT', 'NONE'),
('Hermit', 0.0, true, 15, 25, 240, 'PEASANT', 'NONE'),
('Retired', 0.0, true, 10, 5, 600, 'PEASANT', 'NONE');

